### PR TITLE
Terminating replacements for transaction function

### PR DESCRIPTION
**Pull request by thomassa**
The Xs_client_unix.transaction function would retry for ever if some
client were to keep making writes conflicting with the transaction.

This commit replaces `transaction` with `transaction_one_try` and
`transaction_attempts` which will make only a limited number of
attempts before abandoning the transaction on conflict and passing
the Eagain exception up to the caller.

### CODE REVIEW

**Comment by thomassa** [comment]
This pull-request is one way we could fix issue #29

**Comment by jonludlam** [comment]
This PR breaks the interface. How about changing the transaction function to take an `on_conflict : unit -> unit IO.t` optional param in which you can implement whatever conflict resolution policy you like? ie., backoff, delay, number of retries, whatever?

**Comment by thomassa** [comment]
@jonludlam wrote:
> This PR breaks the interface.

Yes, breaking the interface is a conscious choice, in order to force authors of client code to choose what their software should do when conflicts occur.
> How about changing the transaction function to take an on_conflict : unit -> unit IO.t optional param in which you can implement whatever conflict resolution policy you like? ie., backoff, delay, number of retries, whatever?

An `on_conflict` parameter like that is one of the approaches I mentioned on #29.
Compared to a simple attempts-counter, that approach requires more effort from the authors of client code that uses this library.

If that degree of flexibility is required, then I think building a custom loop around the `transaction_one_try` function would be at least as convenient as writing a custom `on_conflict` function to pass to a function like `transaction on_conflict client f`.

Note that the `on_conflict` would need to be able to raise an exception or otherwise signal to the caller of `transaction` that the transaction failed, and the calling code would have to avoid attempting any subsequent operations that rely on the transaction having been done.

**Comment by jonludlam** [comment]
Actually, looking again at the code, the on_conflict thing would only make sense if it needed to keep any state in the loop, but I don't think it does. So now I think we should just not bother catching the Eagain and let the caller handle it, as your transaction_one_try does. Out of interest, how many users are there of the transaction function? I suspect it actually might be quite small.

I'm still not convinced about the number-of-retries thing though - what would be the recommended number to pass in?

**Comment by thomassa** [comment]
In any case, I'm not aware of any use-cases where any fancy retry strategy would be needed.
For XenServer (if using a version of XenStore with @jjd27's replay-based transaction-merging algorithm) a simple single attempt ought to be enough (since there should never be any opportunity conflicts), but I would be inclined to specify a small handful of retries (perhaps five) so as to cope with occasional accidental conflicts but give up when faced with persistent conflicts.

As for the number of users, in XenServer this transaction is called only by a single wrapper function (also called `transaction`), which has a very similar interface. That function in turn is called from about 23 places in `xenopsd-xc`.

I have no idea how many users there are in Mirage or other software.

**Comment by thomassa** [comment]
I've added a commit to reinstate the original function alongside the new ones, with comments saying it is deprecated and warning that it is not guaranteed ever to return.

**Comment by jonludlam** [comment]
I think that's sensible.

**Comment by jonludlam** [comment]
LGTM.

**Pull request merged**
