### PR TITLE
compile with -safe_string to make it ready for ocaml 4.06

### PR DESCRIPTION
**Pull request by cfcs**

### CODE REVIEW

**Comment by lindig** [comment]
This moves the code to immutable strings and looks good. I'll try to find another reviewer.

**Comment by cfcs** [comment]
I tried not to change the code or existing interfaces too much.
For instance I think `hexify`/`unhexify` could be replaced with `String.init` blocks instead of the copying operation from `bytes` to `string`, but I thought it best to get this merged first, and then tackle optimizations later: https://github.com/mirage/ocaml-xenstore/pull/35/files#diff-2ac2f8b83e6d1b51eb45fbacddbc312aR90

**Comment by djs55** [comment]
Should we mirror the conventions of the standard library and change `write` to look like `Unix.write`? i.e.
```ocaml
val write : file_descr -> bytes -> int -> int -> int
```
I did this with [shared-memory-ring](https://github.com/mirage/shared-memory-ring/pull/35). I suspect there is some code somewhere (in mirage-platform?) that instantiates the client functor with the shared-memory-ring for I/O, using `bytes` would make that smoother.

**Comment by cfcs** [comment]
You could also add a `write_bytes` alternative?

**Comment by rgrinberg** [comment]
Ping? I need this for conduit-mirage + safe-string.

**Pull request merged**
